apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-webapp
  template:
    metadata:
      labels:
        app: mini-webapp
    spec:
      containers:
      - name: mini-webapp
        image: Devops357/mini-webapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mini-webapp-service
spec:
  selector:
    app: mini-webapp
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
