trigger:
  branches:
    include:
      - main
pool:
    name: azurepool

jobs:
 - job: creating a aks
   displayName: 'create a aks'
   steps:
   - task: AKS@3
   - script: |
       az aks create --resourcce-group rgname --name myaks --node-count 3 --location eastus --generate-ssh-keys
