trigger:
  branches:
    include:
      - main
pool:
    name: azurepool

jobs:
 - job: createAksCluster
   displayName: 'create a aks'
   steps:
   - task: AzureCLI@2
   - script: |
       az aks create --resource-group user-omusgtvijdoy --name myaks1 --node-count 3 --location eastus --generate-ssh-keys
