trigger:
  branches:
    include:
      - main

pool:
  name: azurepool

jobs:
  - job: createAksCluster
    displayName: 'Create AKS Cluster'
    steps:
      - script: |
          echo "Creating AKS..."
          az aks create \
            --resource-group user-lesutvpkrxjr \
            --name myaks1 \
            --node-count 3 \
            --location eastus \
            --generate-ssh-keys

          echo "Setting kubeconfig and listing nodes:"
          az aks get-credentials \
            --resource-group user-lesutvpkrxjr \
            --name myaks1 \
            --overwrite-existing
          kubectl get nodes
          sudo snap install kubectl --classic
        displayName: Create AKS Cluster (CLI script)
