trigger:
  branches:
    include:
      - main

pool:
  name: azurepool  # Replace with your pool name

jobs:
- job: InstallAndConfigureAzureCLI
  displayName: Install Azure CLI and Authenticate
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
      | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/microsoft.gpg
      echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] \
      https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" \
      | sudo tee /etc/apt/sources.list.d/azure-cli.list
      sudo apt-get update
      sudo apt-get install -y azure-cli
    displayName: 'Install Azure CLI & Git'
