apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webpage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webpage
  template:
    metadata:
      labels:
        app: my-webpage
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: webpage
              mountPath: /usr/share/nginx/html
      volumes:
        - name: webpage
          configMap:
            name: my-webpage-config
