trigger:
  branches:
    include:
      - main

pool:
  name: azurepool     # your self-hosted Linux agent pool

jobs:
  - job: terraformSubnet
    displayName: 'Terraform Plan & Apply (Subnet)'
    steps:
      - checkout: self

      - script: |
          sudo apt-get update && sudo apt-get install -y \
          gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg \
          | sudo gpg --dearmor \
          -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
          | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get install -y terraform
          cd terraform
          terraform init
          terraform validate
          terraform plan -out=tfplan
        displayName: 'Terraform Init / Validate / Plan'

      - script: |
          cd terraform
          terraform apply -auto-approve tfplan
        displayName: 'Terraform Apply'
